version: "3"
services:
  db:
    image: postgres
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always
